### ISSUE TITLE
responsive contact form 

### ISSUE THREAD

**Issue by davidpfahler** [excellenteasy/website#13]
contact form looks misplaced when you tap the form field for the first time (zooming issue).
![2013-06-03 11 03 04](https://f.cloud.github.com/assets/908242/598435/ddba29d4-cc2c-11e2-8ddc-7940880981fc.png)

**Comment by boennemann** [comment]
The website is fully responsive, it's iOS behavior to zoom.

You can turn off the zoom but that's not a good practice for websites (vs. web apps).

**Comment by davidpfahler** [comment]
So we won' t "fix" it? If so, pls close.
