### ISSUE TITLE
jekyll doesn't copy assets

### ISSUE THREAD

**Issue by davidpfahler** [excellenteasy/website#14]
`build/blog/assets/` only contains `js` folder, but should include css and img as well. This is way it's not update/uploaded to s3.

**Comment by boennemann** [comment]
but why can I test the site locally then?

**Comment by boennemann** [comment]
> why can I test the site locally then?

Actually this behavior hints at a bug in the dist task vs. the build task, but not with jekyll @davidpfahler

**Comment by camcollins** [comment]
I noticed when I attempt to open my local build/index.html file in a browser it can't find the CSS. Didn't troubleshoot beyond observing this.

**Comment by davidpfahler** [comment]
Now it works. The only thing I noticed that I changed is I installed `rdiscount` as required by README.md. Hope it works for everybody now.

**Comment by boennemann** [comment]
so it fixes deploying, too?

**Comment by boennemann** [comment]
I never realized that the build script manually copies files... should be fixed now. d4ed9ce7006762e92f58198b8fc75dec9bb83763
