### ISSUE TITLE
logo at the top should display name

### ISSUE THREAD

**Issue by davidpfahler** [excellenteasy/website#15]
I'm convinced our name should not be hidden on the homepage "behind" the logo. I think it's too hard to discover and you can't instantly verify if you are on the site you looked for (namely the site of a company called "excellenteasy"). Here is a concept I'd like to suggest.

Display the logo with the text to the right of it on each site incl. blog and its posts for let's say 10 seconds. Then the logo "eats up" the text by animating to it's final position and the text is only visible when hovering (like it is now). 

Where we place the logo+name isn't relevant to me, only that it is the same place. It can either be in the center or at the left but not mixed (like it is now between homepage and blog).

**Comment by boennemann** [comment]
we should also match the margin of the logo, so that if you change from blog to website it has the exact same position.
