### ISSUE TITLE
Task to prepare upload folder

### ISSUE THREAD

**Issue by boennemann** [excellenteasy/website#17]
We should have a task that prepares an upload folder for FTP/scp. This means it should only contain .html.gz, .xml and .json. Missed something?

**Comment by boennemann** [comment]
Not sure how this works currently, but we are serving static .gz for html, right @davidpfahler?
Would this be possible for xml and json, too, and is there a fallback to the none .gz version?

If all of these files could be served compressed this task is as easy as changing the target of the compression task.

**Comment by davidpfahler** [comment]
NGINX serves static .gz for HTML files. We do not compress json or xml. To be honest, I don't think it's worth the hassle. Not even sure how browsers handle gzipped json or rss readers xml respectively.

For html, scp is really simple as you said.

**Comment by boennemann** [comment]
JSON and XML are gzipped, the only question left is if nginx serves precompressed files. Can't find the setting in nginx

**Comment by boennemann** [comment]
bam found it. everything fine. will push it soon

**Comment by davidpfahler** [comment]
Ah sorry I didn't understand your question. Yes it does serve compressed files, but I only tested it for `.html.gz`. I would suspect that it also works to other filetypes, but you need to test. An easy way of testing this is only uploading the .gz version and see if the result changes.
