### ISSUE TITLE
Conversion Optimisation

### ISSUE THREAD

**Issue by boennemann** [excellenteasy/website#24]
Great actionable advise from the DC: http://www.dynamitecircle.com/forum/topics/practical-tips-to-increase-conversions
- [x] Change the color of the CTA button to green or orange
- [x] use images for testimonials (Cam yep, Patrice yep, Albrecht yep)
- [ ] state that the sign-up takes only 30seconds
- [x] state that we'll never share e-mails
- [ ] we still need a phone number
- [ ] social proof, we need an about page/section
- [ ] rewrite headline (make a better USP!)
- [ ] portfolio / screenshots of launchtracker, timeclock, ...
- [ ] add a video (not sure what it should say, but essential for SEO)

**Comment by davidpfahler** [comment]
Albrecht yep. Just need to get one that's ok. Round bubbles I'd say?

What I'd like to add to the todo list is
- [ ] subscribe to mailing list on the blog
- [ ] incentive to subscribe to mailing list (e.g. whitepaper)

**Comment by boennemann** [comment]
We need to create a little more scarcity around our product, instead of `Let's take the first step`, we should go along the lines of 

> Request early access to our conversion service

a) actually this more honest, b) it excuses for some hiccups on our side, and most importantly c) It will psychologically trick visitors into giving their e-mails away, because you know, they could miss out on something!11

Oh and of course we need to slip the e-mail feedback into the copy.

**Comment by davidpfahler** [comment]
:+1:
