### ISSUE TITLE
Dynamic Share/Like/Upvote buttons

### ISSUE THREAD

**Issue by boennemann** [excellenteasy/website#25]
Based on `document.referrer` we can see if people are coming from HackerNews, Twitter, G+, Facebook, Reddit or whatever.

Based on the specific referrer we could then display dynamic messages at the end of our blogposts:

> Did you like our article? Don't forget to up-vote it on HackerNews.
> 
> If you liked reading our blogpost please share it with your followers.

We could spin these messages and measure their conversions

**Comment by davidpfahler** [comment]
I like a lot.
