### ISSUE TITLE
Image captions

### ISSUE THREAD

**Issue by boennemann** [excellenteasy/website#4]
Image captions need to be styled. Specifically they need to have a smaller font, and be centered.

**Comment by boennemann** [comment]
https://github.com/excellenteasy/website/commit/149fa898ca3141016734c216c994b9914cd0dac9

**Comment by davidpfahler** [comment]
Shouldn't this be part of the [image_block plugin script](https://github.com/excellenteasy/website/blob/master/src/blog/_plugins/image_block.rb)? If you agree, we can make a new issue and one of us can fix it.

**Comment by boennemann** [comment]
I agree, you should fix it.
