### ISSUE TITLE
Create 3xx.html 4xx.html and 5xx.html pages / error pages

### ISSUE THREAD

**Issue by boennemann** [excellenteasy/website#6]

**Comment by boennemann** [comment]
embed search on every page #7

**Comment by boennemann** [comment]
http://excellenteasy.com/thispagedoesntexistdude/

**Comment by davidpfahler** [comment]
Awesome, dude.

**Comment by boennemann** [comment]
I still need to separate 4xx and 5xx because the copy should be slightly different
