### ISSUE TITLE
Decide on whether to use comments/disqus

### ISSUE THREAD

**Issue by boennemann** [excellenteasy/website#8]
SetUp is as easy as pie, already got it working locally in 2minutes. More of a strategy question. @davidpfahler 

disqus somehow managed to get crawled by google, and it monitors social reactions.

**Comment by boennemann** [comment]
@davidpfahler ??

**Comment by camcollins** [comment]
+1 disqus. Social bookmarking, back links, crawl friendly, it's all there.

**Comment by boennemann** [comment]
If we use comments I'd choose disqus,  too.  Only question left: Do we
want/need comments?

**Comment by camcollins** [comment]
I think it's imperative as a means to communicate with our fans.

**Comment by davidpfahler** [comment]
SEOwise it's definitely positive, the question is to what degree. I especially see comments as problematic when you don't have traffic, yet. This leads to either a) no comments, which exposes that you have no traffic, not good, or b) spam comments, which are a hassle to administrate etc. 

Hence, I'm firmly against comments as long as there is virtually no one to comment. It we get traffic and start ranking, I'd agree to use disqus.

**Comment by boennemann** [comment]
Spam won't be a problem with Disqus (another upside), but it'll certainly add unnecessary load time (We can fix this by loading it `onscroll` or similiar).

As we are indexed by Google now, I suggest implementing #9 first. Then we can continue this discussion with more data to feed it.

**Comment by camcollins** [comment]
I disagree David. Blogging and Comments are a slow, steady drip that can take years to develop. Lets post this question in the DC or send a PM to Dan Andrews.

**Comment by davidpfahler** [comment]
DC was 100% pro comments. Sometimes asking is the simplest way ;) So, I guess we are going to go with Disqus.

**Comment by boennemann** [comment]
Awesome! Please give me your disqus usernames/emails so I can add you to the moderator team.

**Comment by davidpfahler** [comment]
I have no such thing. Do I need to sign up? Seems like it works with google accounts.

**Comment by boennemann** [comment]
Yes please sign up, as I said you need an account to be on the moderator team.

**Comment by davidpfahler** [comment]
username: davidpfahler

**Comment by boennemann** [comment]
Okay guys, comments are now live. As always it turned out that enabling them was a matter of 2minutes, but going the last mile and using disqus without totally destroying pagespeed took it's time.

I've implemented disqus in a way that it is only loaded once you scroll past 70% of our page.
